// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package com.energy.smartcity.traffic;

public interface autoOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.autoOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AutoTraffic = 1;</code>
   */
  java.lang.String getAutoTraffic();
  /**
   * <code>string AutoTraffic = 1;</code>
   */
  com.google.protobuf.ByteString
      getAutoTrafficBytes();
}
