// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package com.energy.smartcity.traffic;

public interface emerTrafficOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.emerTrafficOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string EmergencyTraffic = 1;</code>
   */
  java.lang.String getEmergencyTraffic();
  /**
   * <code>string EmergencyTraffic = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmergencyTrafficBytes();
}
