// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package com.energy.smartcity.traffic;

public interface signalsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.signalsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AutoSignals = 1;</code>
   */
  java.lang.String getAutoSignals();
  /**
   * <code>string AutoSignals = 1;</code>
   */
  com.google.protobuf.ByteString
      getAutoSignalsBytes();
}
