// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface frontOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.frontOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SeafrontReply = 1;</code>
   */
  java.lang.String getSeafrontReply();
  /**
   * <code>string SeafrontReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getSeafrontReplyBytes();
}
