// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface frontRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.frontRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Seafront = 1;</code>
   */
  java.lang.String getSeafront();
  /**
   * <code>string Seafront = 1;</code>
   */
  com.google.protobuf.ByteString
      getSeafrontBytes();
}
