// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface rescuersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.rescuersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string MedicalRescuers = 1;</code>
   */
  java.lang.String getMedicalRescuers();
  /**
   * <code>string MedicalRescuers = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicalRescuersBytes();
}
