// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface rescuersReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.rescuersReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string MedicalRescuersReply = 1;</code>
   */
  java.lang.String getMedicalRescuersReply();
  /**
   * <code>string MedicalRescuersReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicalRescuersReplyBytes();
}
