// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public final class SeafrontServiceImpl {
  private SeafrontServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_frontRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_frontRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_stationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_stationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_rescuersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_rescuersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_frontOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_frontOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_stationsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_stationsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_rescuersReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_rescuersReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016seafront.proto\022\021SmartCityServices\" \n\014f" +
      "rontRequest\022\020\n\010Seafront\030\001 \001(\t\"%\n\017station" +
      "sRequest\022\022\n\nLifeguards\030\001 \001(\t\"*\n\017rescuers" +
      "Request\022\027\n\017MedicalRescuers\030\001 \001(\t\"%\n\014fron" +
      "tOnReply\022\025\n\rSeafrontReply\030\001 \001(\t\"(\n\rstati" +
      "onsReply\022\027\n\017LifeguardsReply\030\001 \001(\t\"-\n\rres" +
      "cuersReply\022\034\n\024MedicalRescuersReply\030\001 \001(\t" +
      "2\221\002\n\016SeafrontLights\022O\n\tseaLights\022\037.Smart" +
      "CityServices.frontRequest\032\037.SmartCitySer" +
      "vices.frontOnReply\"\000\022[\n\021lifeguardStation" +
      "s\022\".SmartCityServices.stationsRequest\032 ." +
      "SmartCityServices.stationsReply\"\000\022Q\n\007med" +
      "ical\022\".SmartCityServices.rescuersRequest" +
      "\032 .SmartCityServices.rescuersReply\"\000B6\n\035" +
      "com.energy.smartcity.seafrontB\023SeafrontS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartCityServices_frontRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartCityServices_frontRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_frontRequest_descriptor,
        new java.lang.String[] { "Seafront", });
    internal_static_SmartCityServices_stationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartCityServices_stationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_stationsRequest_descriptor,
        new java.lang.String[] { "Lifeguards", });
    internal_static_SmartCityServices_rescuersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartCityServices_rescuersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_rescuersRequest_descriptor,
        new java.lang.String[] { "MedicalRescuers", });
    internal_static_SmartCityServices_frontOnReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartCityServices_frontOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_frontOnReply_descriptor,
        new java.lang.String[] { "SeafrontReply", });
    internal_static_SmartCityServices_stationsReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartCityServices_stationsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_stationsReply_descriptor,
        new java.lang.String[] { "LifeguardsReply", });
    internal_static_SmartCityServices_rescuersReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartCityServices_rescuersReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_rescuersReply_descriptor,
        new java.lang.String[] { "MedicalRescuersReply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
