// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface stationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.stationsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Lifeguards = 1;</code>
   */
  java.lang.String getLifeguards();
  /**
   * <code>string Lifeguards = 1;</code>
   */
  com.google.protobuf.ByteString
      getLifeguardsBytes();
}
