// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

public interface stationsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.stationsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string LifeguardsReply = 1;</code>
   */
  java.lang.String getLifeguardsReply();
  /**
   * <code>string LifeguardsReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getLifeguardsReplyBytes();
}
