// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

/**
 * Protobuf type {@code SmartCityServices.stationsReply}
 */
public  final class stationsReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartCityServices.stationsReply)
    stationsReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stationsReply.newBuilder() to construct.
  private stationsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stationsReply() {
    lifeguardsReply_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private stationsReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            lifeguardsReply_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.energy.smartcity.seafront.stationsReply.class, com.energy.smartcity.seafront.stationsReply.Builder.class);
  }

  public static final int LIFEGUARDSREPLY_FIELD_NUMBER = 1;
  private volatile java.lang.Object lifeguardsReply_;
  /**
   * <code>string LifeguardsReply = 1;</code>
   */
  public java.lang.String getLifeguardsReply() {
    java.lang.Object ref = lifeguardsReply_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lifeguardsReply_ = s;
      return s;
    }
  }
  /**
   * <code>string LifeguardsReply = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLifeguardsReplyBytes() {
    java.lang.Object ref = lifeguardsReply_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lifeguardsReply_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLifeguardsReplyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lifeguardsReply_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLifeguardsReplyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lifeguardsReply_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.energy.smartcity.seafront.stationsReply)) {
      return super.equals(obj);
    }
    com.energy.smartcity.seafront.stationsReply other = (com.energy.smartcity.seafront.stationsReply) obj;

    boolean result = true;
    result = result && getLifeguardsReply()
        .equals(other.getLifeguardsReply());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIFEGUARDSREPLY_FIELD_NUMBER;
    hash = (53 * hash) + getLifeguardsReply().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.energy.smartcity.seafront.stationsReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SmartCityServices.stationsReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartCityServices.stationsReply)
      com.energy.smartcity.seafront.stationsReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.energy.smartcity.seafront.stationsReply.class, com.energy.smartcity.seafront.stationsReply.Builder.class);
    }

    // Construct using com.energy.smartcity.seafront.stationsReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lifeguardsReply_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsReply_descriptor;
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsReply getDefaultInstanceForType() {
      return com.energy.smartcity.seafront.stationsReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsReply build() {
      com.energy.smartcity.seafront.stationsReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsReply buildPartial() {
      com.energy.smartcity.seafront.stationsReply result = new com.energy.smartcity.seafront.stationsReply(this);
      result.lifeguardsReply_ = lifeguardsReply_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.energy.smartcity.seafront.stationsReply) {
        return mergeFrom((com.energy.smartcity.seafront.stationsReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.energy.smartcity.seafront.stationsReply other) {
      if (other == com.energy.smartcity.seafront.stationsReply.getDefaultInstance()) return this;
      if (!other.getLifeguardsReply().isEmpty()) {
        lifeguardsReply_ = other.lifeguardsReply_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.energy.smartcity.seafront.stationsReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.energy.smartcity.seafront.stationsReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object lifeguardsReply_ = "";
    /**
     * <code>string LifeguardsReply = 1;</code>
     */
    public java.lang.String getLifeguardsReply() {
      java.lang.Object ref = lifeguardsReply_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lifeguardsReply_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string LifeguardsReply = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLifeguardsReplyBytes() {
      java.lang.Object ref = lifeguardsReply_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lifeguardsReply_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string LifeguardsReply = 1;</code>
     */
    public Builder setLifeguardsReply(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lifeguardsReply_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string LifeguardsReply = 1;</code>
     */
    public Builder clearLifeguardsReply() {
      
      lifeguardsReply_ = getDefaultInstance().getLifeguardsReply();
      onChanged();
      return this;
    }
    /**
     * <code>string LifeguardsReply = 1;</code>
     */
    public Builder setLifeguardsReplyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lifeguardsReply_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartCityServices.stationsReply)
  }

  // @@protoc_insertion_point(class_scope:SmartCityServices.stationsReply)
  private static final com.energy.smartcity.seafront.stationsReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.energy.smartcity.seafront.stationsReply();
  }

  public static com.energy.smartcity.seafront.stationsReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<stationsReply>
      PARSER = new com.google.protobuf.AbstractParser<stationsReply>() {
    @java.lang.Override
    public stationsReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stationsReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<stationsReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stationsReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.energy.smartcity.seafront.stationsReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

