// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seafront.proto

package com.energy.smartcity.seafront;

/**
 * Protobuf type {@code SmartCityServices.stationsRequest}
 */
public  final class stationsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartCityServices.stationsRequest)
    stationsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stationsRequest.newBuilder() to construct.
  private stationsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stationsRequest() {
    lifeguards_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private stationsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            lifeguards_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.energy.smartcity.seafront.stationsRequest.class, com.energy.smartcity.seafront.stationsRequest.Builder.class);
  }

  public static final int LIFEGUARDS_FIELD_NUMBER = 1;
  private volatile java.lang.Object lifeguards_;
  /**
   * <code>string Lifeguards = 1;</code>
   */
  public java.lang.String getLifeguards() {
    java.lang.Object ref = lifeguards_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lifeguards_ = s;
      return s;
    }
  }
  /**
   * <code>string Lifeguards = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLifeguardsBytes() {
    java.lang.Object ref = lifeguards_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lifeguards_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLifeguardsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lifeguards_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLifeguardsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lifeguards_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.energy.smartcity.seafront.stationsRequest)) {
      return super.equals(obj);
    }
    com.energy.smartcity.seafront.stationsRequest other = (com.energy.smartcity.seafront.stationsRequest) obj;

    boolean result = true;
    result = result && getLifeguards()
        .equals(other.getLifeguards());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIFEGUARDS_FIELD_NUMBER;
    hash = (53 * hash) + getLifeguards().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.energy.smartcity.seafront.stationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.energy.smartcity.seafront.stationsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SmartCityServices.stationsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartCityServices.stationsRequest)
      com.energy.smartcity.seafront.stationsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.energy.smartcity.seafront.stationsRequest.class, com.energy.smartcity.seafront.stationsRequest.Builder.class);
    }

    // Construct using com.energy.smartcity.seafront.stationsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lifeguards_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.energy.smartcity.seafront.SeafrontServiceImpl.internal_static_SmartCityServices_stationsRequest_descriptor;
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsRequest getDefaultInstanceForType() {
      return com.energy.smartcity.seafront.stationsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsRequest build() {
      com.energy.smartcity.seafront.stationsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.energy.smartcity.seafront.stationsRequest buildPartial() {
      com.energy.smartcity.seafront.stationsRequest result = new com.energy.smartcity.seafront.stationsRequest(this);
      result.lifeguards_ = lifeguards_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.energy.smartcity.seafront.stationsRequest) {
        return mergeFrom((com.energy.smartcity.seafront.stationsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.energy.smartcity.seafront.stationsRequest other) {
      if (other == com.energy.smartcity.seafront.stationsRequest.getDefaultInstance()) return this;
      if (!other.getLifeguards().isEmpty()) {
        lifeguards_ = other.lifeguards_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.energy.smartcity.seafront.stationsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.energy.smartcity.seafront.stationsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object lifeguards_ = "";
    /**
     * <code>string Lifeguards = 1;</code>
     */
    public java.lang.String getLifeguards() {
      java.lang.Object ref = lifeguards_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lifeguards_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Lifeguards = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLifeguardsBytes() {
      java.lang.Object ref = lifeguards_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lifeguards_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Lifeguards = 1;</code>
     */
    public Builder setLifeguards(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lifeguards_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Lifeguards = 1;</code>
     */
    public Builder clearLifeguards() {
      
      lifeguards_ = getDefaultInstance().getLifeguards();
      onChanged();
      return this;
    }
    /**
     * <code>string Lifeguards = 1;</code>
     */
    public Builder setLifeguardsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lifeguards_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartCityServices.stationsRequest)
  }

  // @@protoc_insertion_point(class_scope:SmartCityServices.stationsRequest)
  private static final com.energy.smartcity.seafront.stationsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.energy.smartcity.seafront.stationsRequest();
  }

  public static com.energy.smartcity.seafront.stationsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<stationsRequest>
      PARSER = new com.google.protobuf.AbstractParser<stationsRequest>() {
    @java.lang.Override
    public stationsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stationsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<stationsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stationsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.energy.smartcity.seafront.stationsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

