// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public interface emergencyOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.emergencyOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emergency = 1;</code>
   */
  java.lang.String getEmergency();
  /**
   * <code>string emergency = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmergencyBytes();
}
