// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public interface emergencyOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.emergencyOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emergencyOn = 1;</code>
   */
  java.lang.String getEmergencyOn();
  /**
   * <code>string emergencyOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmergencyOnBytes();
}
