// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public final class ParkServiceImpl {
  private ParkServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_emergencyOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_emergencyOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_polesOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_polesOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_polesOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_polesOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_emergencyOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_emergencyOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_polesOnReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_polesOnReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartCityServices_polesOffReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartCityServices_polesOffReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npark.proto\022\021SmartCityServices\"\'\n\022emerg" +
      "encyOnRequest\022\021\n\temergency\030\001 \001(\t\"\037\n\016pole" +
      "sOnRequest\022\r\n\005poles\030\001 \001(\t\" \n\017polesOffReq" +
      "uest\022\r\n\005poles\030\001 \001(\t\"\'\n\020emergencyOnReply\022" +
      "\023\n\013emergencyOn\030\001 \001(\t\"\037\n\014polesOnReply\022\017\n\007" +
      "polesOn\030\001 \001(\t\"!\n\rpolesOffReply\022\020\n\010polesO" +
      "ff\030\001 \001(\t2\214\002\n\nParkLights\022Y\n\tEmergency\022%.S" +
      "martCityServices.emergencyOnRequest\032#.Sm" +
      "artCityServices.emergencyOnReply\"\000\022O\n\007Po" +
      "lesOn\022!.SmartCityServices.polesOnRequest" +
      "\032\037.SmartCityServices.polesOnReply\"\000\022R\n\010P" +
      "olesOff\022\".SmartCityServices.polesOffRequ" +
      "est\032 .SmartCityServices.polesOffReply\"\000B" +
      ".\n\031com.energy.smartcity.parkB\017ParkServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartCityServices_emergencyOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartCityServices_emergencyOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_emergencyOnRequest_descriptor,
        new java.lang.String[] { "Emergency", });
    internal_static_SmartCityServices_polesOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartCityServices_polesOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_polesOnRequest_descriptor,
        new java.lang.String[] { "Poles", });
    internal_static_SmartCityServices_polesOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartCityServices_polesOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_polesOffRequest_descriptor,
        new java.lang.String[] { "Poles", });
    internal_static_SmartCityServices_emergencyOnReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartCityServices_emergencyOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_emergencyOnReply_descriptor,
        new java.lang.String[] { "EmergencyOn", });
    internal_static_SmartCityServices_polesOnReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartCityServices_polesOnReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_polesOnReply_descriptor,
        new java.lang.String[] { "PolesOn", });
    internal_static_SmartCityServices_polesOffReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartCityServices_polesOffReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartCityServices_polesOffReply_descriptor,
        new java.lang.String[] { "PolesOff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
