// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public interface polesOnReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.polesOnReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string polesOn = 1;</code>
   */
  java.lang.String getPolesOn();
  /**
   * <code>string polesOn = 1;</code>
   */
  com.google.protobuf.ByteString
      getPolesOnBytes();
}
