// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public interface polesOffReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.polesOffReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string polesOff = 1;</code>
   */
  java.lang.String getPolesOff();
  /**
   * <code>string polesOff = 1;</code>
   */
  com.google.protobuf.ByteString
      getPolesOffBytes();
}
