// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: park.proto

package com.energy.smartcity.park;

public interface polesOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartCityServices.polesOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string poles = 1;</code>
   */
  java.lang.String getPoles();
  /**
   * <code>string poles = 1;</code>
   */
  com.google.protobuf.ByteString
      getPolesBytes();
}
